### ISSUE TITLE
비밀번호 유효성 체크가 잘못되었음

### ISSUE THREAD

**Issue by cos18** [somul-project/somul-system-backend#7]
https://github.com/somul-project/somul-system-backend/blob/4c4bb3fae475bd203734af1833e18ce2a0db3476/src/api/auth/authHandler.ts#L51-L54

현제 비밀번호의 유효성은 '8글자 이상의 숫자와 문자 조합'이나 현재 8글자의 영어로 이루어져 있거나 8글자의 숫자로 이루어져 있는 경우 걸러내지 않는 정규식을 사용하고 있는 것 같습니다.

프론트에서 사용하고 있는 정규식은 다음과 같습니다.
`/^(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]{8,}$/i`

**Comment by harrydrippin** [comment]
이 경우, 단순하게 전체 String에 대하여 문자의 갯수와 숫자의 갯수를 센 후 다음 조건을 만족하면 됩니다.

1. 문자의 갯수가 0이 아니다
2. 숫자의 갯수가 0이 아니다
3. 문자의 갯수와 숫자의 갯수를 더한 값이 8 이상이다

꼭 정규식을 고집하여 사용할 필요는 없겠습니다. 실제로 제가 말씀드린 로직보다 느릴 수도 있어요.

**Comment by ehdgus8077** [comment]
> 이 경우, 단순하게 전체 String에 대하여 문자의 갯수와 숫자의 갯수를 센 후 다음 조건을 만족하면 됩니다.
> 여기서 문자란 `a-zA-Z~!@#$%\^&*()-+=`를 의미하며 숫자는 `0-9`를 의미합니다.
> 
> 1. 영어 대소문자와 숫자가 한 번씩은 나타난다
> 2. 문자의 갯수가 0이 아니다
> 3. 숫자의 갯수가 0이 아니다
> 4. 문자의 갯수와 숫자의 갯수를 더한 값이 8 이상이다
> 
> 1번과 2번을 뺀 경우 아마 다음 정규식으로 처리가 가능할 듯 합니다.
> 
> `/^(?=.*?[A-Za-z])(?=.*?[0-9]).{8,}$/`
> 
> 위 정규식을 통과한 비밀번호에 대해서 1번과 2번 체크만 추가로 해주면 될 것 같습니다.

몇 가지 질문이 있습니다.
1. 정규식으로만 처리하면 안되는 이유를 알 수 있을까요? 
2.`/^(?=.*?[A-Za-z])(?=.*?[0-9]).{8,}$/ `같은 정규식은 특수문자를 포함할 수 없습니다. 혹시 의도를 하신건가요?

제 생각에는 
`/^(?=.*?[A-Za-z])(?=.*?[0-9])(?=.*[A-Za-z!@#$%^&+=_]).{8,15}$/
`
를 사용해서 숫자와 알파벳은 필수로 들어가야하고, 특수문자는 선택적으로 포함해야하는 정규식을 추가하면 되지 않을까요? 또한 글자수 제한도 검사를 하기 때문에 더 깔끔할 것 같습니다.

**Comment by harrydrippin** [comment]
제시하신 식으로 진행하면 될 것 같습니다.

**Comment by cos18** [comment]
> 2. .`/^(?=.*?[A-Za-z])(?=.*?[0-9]).{8,}$/ `같은 정규식은 특수문자를 포함할 수 없습니다. 혹시 의도를 하신건가요?

앗 제가 그 생각을 못했네요. 의도한 것은 아니고 제 실수인 것 같습니다 😅

**Comment by ehdgus8077** [comment]
반영했습니다!
